AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  thesapling-stream-api

  Sample SAM Template for thesapling-stream-api

Resources:
  CameraPositionsFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AccessToCameraPositionsDatabase
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                  - dynamodb:Query
                  - dynamodb:Scan
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                Resource: !GetAtt CameraPositionsDatabase.Arn  

  CameraPositionsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Role: !GetAtt CameraPositionsFunctionRole.Arn
      CodeUri: camera_positions/
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures:
        - x86_64

  CameraPositionsDatabase:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: CameraPositions
      AttributeDefinitions:
        - AttributeName: creator
          AttributeType: S
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: creator
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: creator-index
          KeySchema:
            - AttributeName: creator
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: id-index
          KeySchema:
            - AttributeName: id
              KeyType: HASH
          Projection:
            ProjectionType: ALL